### ISSUE TITLE
Make EmojiPasta a Pip Installable

### ISSUE THREAD

**Issue by khurd21** [SilasStokes/pymessage_gpt_bot#3]
https://github.com/Kevinpgalligan/EmojipastaBot

Currently the EmojiPasta dependency we are using does not have a pip install. Add this to project for ease of bringing in the dependency.

**Comment by SilasStokes** [comment]
updated with [0ae0cd5](https://github.com/SilasStokes/pymessage_gpt_bot/commit/0ae0cd53731442b5eb632667af770efb1dd549a8). Made an emojipasta pip package here:  https://github.com/SilasStokes/emojipasta
